DROP TABLE IF EXISTS ranking;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email VARCHAR(128) NOT NULL UNIQUE,
  password_hash VARCHAR(128) NOT NULL
);

CREATE TABLE teams(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE matches(
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  team0 INTEGER NOT NULL, 
  team1 INTEGER NOT NULL CHECK(team0<>team1),
  score0 INTEGER NOT NULL, 
  score1 INTEGER NOT NULL,
  date DATETIME,
  UNIQUE (team0, team1),
  --FOREIGN KEY(team0, team1) REFERENCES teams(id, id)
  FOREIGN KEY(team0) REFERENCES teams(id),
  FOREIGN KEY(team1) REFERENCES teams(id)
);

CREATE TABLE ranking(
  rank INTEGER UNIQUE,
  team_id INTEGER PRIMARY KEY,
  match_played_count INTEGER NOT NULL,
  match_won_count INTEGER NOT NULL, 
  match_lost_count INTEGER NOT NULL, 
  draw_count INTEGER NOT NULL,
  goal_for_count INTEGER NOT NULL, 
  goal_against_count INTEGER NOT NULL,
  goal_difference INTEGER NOT NULL,
  points INTEGER NOT NULL,
  FOREIGN KEY (team_id) REFERENCES teams(id)
);